driverClassName=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:3306/gps?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
username=root
password=3224591

maxActive=10
maxIdle=5
initialSize=5
minIdle=5
maxWait=60000
testWhileIdle=true
testOnBorrow=false
testOnReturn=false
poolPreparedStatements=true